
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sell?useUnicode=true&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:

debug: true