#service≈‰÷√
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: prod
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false

  #ª∫¥Êœ‡πÿ
  cache:
    type: ehcache

